-- The tables, on any Postgres. What TimescaleDB adds on top of them is the
-- second migration, which has a variant for a server that does not have it.
--
-- Everything is IF NOT EXISTS so a file interrupted halfway can simply be run
-- again; the runner applies statements one at a time and outside a transaction,
-- because creating a continuous aggregate is not allowed inside one.
--
-- Identity is BY DEFAULT rather than ALWAYS, so a restore or a backfill can
-- write explicit ids: issue and project ids are in dashboard URLs, and
-- renumbering them would break every saved link.
CREATE TABLE IF NOT EXISTS users (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  email TEXT NOT NULL UNIQUE,
  name TEXT NOT NULL DEFAULT '',
  password_hash TEXT NOT NULL,
  locale TEXT NOT NULL DEFAULT '',
  created_at TIMESTAMPTZ NOT NULL
);

CREATE TABLE IF NOT EXISTS auth_tokens (
  token_hash TEXT PRIMARY KEY,
  user_id BIGINT NOT NULL REFERENCES users(id),
  created_at TIMESTAMPTZ NOT NULL,
  expires_at TIMESTAMPTZ NOT NULL
);

CREATE TABLE IF NOT EXISTS projects (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  name TEXT NOT NULL,
  api_key TEXT NOT NULL UNIQUE,
  platform TEXT NOT NULL DEFAULT 'flutter',
  created_by BIGINT,
  created_at TIMESTAMPTZ NOT NULL
);

CREATE TABLE IF NOT EXISTS project_members (
  project_id BIGINT NOT NULL REFERENCES projects(id),
  user_id BIGINT NOT NULL REFERENCES users(id),
  role TEXT NOT NULL DEFAULT 'member',
  PRIMARY KEY(project_id, user_id)
);

-- sessions stays a plain table on purpose. Ingest upserts it by id alone
-- (ON CONFLICT(id)), and a hypertable can only carry a unique index that
-- includes its partitioning column, which would turn every heartbeat into a
-- second row instead of an update.
CREATE TABLE IF NOT EXISTS sessions (
  id TEXT PRIMARY KEY,
  project_id BIGINT NOT NULL REFERENCES projects(id),
  started_at TIMESTAMPTZ NOT NULL,
  last_seen_at TIMESTAMPTZ NOT NULL,
  ended_at TIMESTAMPTZ,
  user_id TEXT NOT NULL DEFAULT '',
  user_json TEXT NOT NULL DEFAULT '{}',
  device_json TEXT NOT NULL DEFAULT '{}',
  props_json TEXT NOT NULL DEFAULT '{}',
  platform TEXT NOT NULL DEFAULT '',
  release TEXT NOT NULL DEFAULT '',
  error_count INTEGER NOT NULL DEFAULT 0,
  event_count INTEGER NOT NULL DEFAULT 0,
  frame_count INTEGER NOT NULL DEFAULT 0,
  ip TEXT NOT NULL DEFAULT '',
  browser TEXT NOT NULL DEFAULT '',
  visitor_key TEXT NOT NULL DEFAULT '',
  current_route TEXT NOT NULL DEFAULT ''
);

CREATE INDEX IF NOT EXISTS sessions_project_seen ON sessions(project_id, last_seen_at DESC);
-- The live view asks for the open sessions of one project, newest first, once a
-- second. Indexing only the open ones keeps that read off the long tail of
-- sessions that have already ended.
CREATE INDEX IF NOT EXISTS sessions_project_live ON sessions(project_id, last_seen_at DESC) WHERE ended_at IS NULL;
CREATE INDEX IF NOT EXISTS sessions_started ON sessions(project_id, started_at);

-- The JSON columns stay TEXT rather than JSONB. What the SDK sent is handed back
-- to the dashboard verbatim, and JSONB would reorder the keys and drop the
-- whitespace; nothing here queries inside a body, so there is nothing to gain
-- for it either.
CREATE TABLE IF NOT EXISTS items (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY,
  session_id TEXT NOT NULL REFERENCES sessions(id),
  project_id BIGINT NOT NULL,
  ts TIMESTAMPTZ NOT NULL,
  type TEXT NOT NULL,
  name TEXT NOT NULL DEFAULT '',
  body_json TEXT NOT NULL DEFAULT '{}',
  issue_id BIGINT,
  PRIMARY KEY(id, ts)
);

CREATE INDEX IF NOT EXISTS items_session_ts ON items(session_id, ts);
CREATE INDEX IF NOT EXISTS items_project_type_ts ON items(project_id, type, ts);
-- ts rides along so GetIssue's "last 50 occurrences, newest first" is an index
-- scan and, on a hypertable, excludes the chunks outside the issue's lifetime.
CREATE INDEX IF NOT EXISTS items_issue_ts ON items(issue_id, ts DESC);

CREATE TABLE IF NOT EXISTS issues (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  project_id BIGINT NOT NULL,
  fingerprint TEXT NOT NULL,
  title TEXT NOT NULL,
  exception TEXT NOT NULL DEFAULT '',
  first_seen TIMESTAMPTZ NOT NULL,
  last_seen TIMESTAMPTZ NOT NULL,
  count INTEGER NOT NULL DEFAULT 0,
  resolved BOOLEAN NOT NULL DEFAULT FALSE,
  UNIQUE(project_id, fingerprint)
);

CREATE INDEX IF NOT EXISTS issues_project_seen ON issues(project_id, last_seen DESC);

-- frames stays a plain table for the same reason sessions does: the row is
-- upserted by (session_id, seq) when the SDK resends a frame, and every row has
-- a PNG next to it in the blob store that a retention policy could not delete.
CREATE TABLE IF NOT EXISTS frames (
  session_id TEXT NOT NULL REFERENCES sessions(id),
  seq INTEGER NOT NULL,
  ts TIMESTAMPTZ NOT NULL,
  width INTEGER NOT NULL,
  height INTEGER NOT NULL,
  taps_json TEXT NOT NULL DEFAULT '[]',
  PRIMARY KEY(session_id, seq)
);
