-- Source maps, so a stack trace from a minified release build can be read.
--
-- The map itself is 10–30 MB of JSON and goes to the blob store next to the
-- replay frames; this table is the index over it — which releases of which
-- project have which files, and what was uploaded when.
CREATE TABLE IF NOT EXISTS release_artifacts (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  project_id BIGINT NOT NULL REFERENCES projects(id),
  release TEXT NOT NULL,
  filename TEXT NOT NULL,
  sha256 TEXT NOT NULL,
  size BIGINT NOT NULL,
  uploaded_at TIMESTAMPTZ NOT NULL,
  -- Uploading the same file for the same release again replaces it, which is
  -- what a rebuilt release needs.
  UNIQUE(project_id, release, filename)
);

CREATE INDEX IF NOT EXISTS release_artifacts_lookup ON release_artifacts(project_id, release);

-- The resolved frames of an error, as `{"frames":[{file,line,column,function}]}`.
--
-- A separate column rather than extra keys inside body_json: what the SDK sent
-- is handed back to the dashboard verbatim, and rewriting it would break that.
-- It also leaves room to fill this in later — a map is often uploaded after the
-- first error of a release has already arrived, and that is an UPDATE here
-- rather than a rewrite of the item.
--
-- NULL on every item that is not an error, which is almost all of them; a null
-- column costs a bit in the row header and nothing else.
ALTER TABLE items ADD COLUMN IF NOT EXISTS symbolicated_json TEXT;
