-- Alert rules and notification channels (email, Slack, webhook) for new issues,
-- regressions, and error rate spikes.

CREATE TABLE IF NOT EXISTS alert_channels (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  project_id BIGINT NOT NULL REFERENCES projects(id) ON DELETE CASCADE,
  name TEXT NOT NULL DEFAULT '',
  kind TEXT NOT NULL, -- 'email', 'slack', 'webhook'
  target TEXT NOT NULL, -- email address, Slack webhook URL, or generic webhook URL
  secret TEXT NOT NULL DEFAULT '', -- HMAC-SHA256 secret for webhook signatures
  created_at TIMESTAMPTZ NOT NULL
);

CREATE INDEX IF NOT EXISTS alert_channels_project ON alert_channels(project_id);

CREATE TABLE IF NOT EXISTS alert_rules (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  project_id BIGINT NOT NULL REFERENCES projects(id) ON DELETE CASCADE,
  name TEXT NOT NULL DEFAULT '',
  kind TEXT NOT NULL, -- 'new_issue', 'regression', 'rate_spike', 'session_crash_free'
  params_json TEXT NOT NULL DEFAULT '{}',
  channel_ids_json TEXT NOT NULL DEFAULT '[]',
  enabled BOOLEAN NOT NULL DEFAULT TRUE,
  created_at TIMESTAMPTZ NOT NULL
);

CREATE INDEX IF NOT EXISTS alert_rules_project ON alert_rules(project_id);

CREATE TABLE IF NOT EXISTS alert_deliveries (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  rule_id BIGINT NOT NULL REFERENCES alert_rules(id) ON DELETE CASCADE,
  channel_id BIGINT NOT NULL REFERENCES alert_channels(id) ON DELETE CASCADE,
  issue_id BIGINT REFERENCES issues(id) ON DELETE SET NULL,
  fingerprint TEXT NOT NULL DEFAULT '',
  sent_at TIMESTAMPTZ NOT NULL,
  status TEXT NOT NULL, -- 'success', 'failed'
  error TEXT NOT NULL DEFAULT ''
);

CREATE INDEX IF NOT EXISTS alert_deliveries_dedup ON alert_deliveries(rule_id, issue_id) WHERE issue_id IS NOT NULL;
CREATE INDEX IF NOT EXISTS alert_deliveries_cooldown ON alert_deliveries(rule_id, sent_at DESC);
