CREATE TABLE IF NOT EXISTS spans (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY,
  project_id BIGINT NOT NULL REFERENCES projects(id) ON DELETE CASCADE,
  session_id TEXT NOT NULL REFERENCES sessions(id) ON DELETE CASCADE,
  ts TIMESTAMPTZ NOT NULL,
  op TEXT NOT NULL DEFAULT '',
  name TEXT NOT NULL DEFAULT '',
  duration_ms DOUBLE PRECISION NOT NULL DEFAULT 0,
  status TEXT NOT NULL DEFAULT 'ok',
  parent_span_id TEXT NOT NULL DEFAULT '',
  span_id TEXT NOT NULL DEFAULT '',
  trace_id TEXT NOT NULL DEFAULT '',
  tags_json TEXT NOT NULL DEFAULT '{}',
  PRIMARY KEY (id, ts)
);

CREATE INDEX IF NOT EXISTS idx_spans_project_op_name_ts ON spans(project_id, op, name, ts DESC);
CREATE INDEX IF NOT EXISTS idx_spans_session_ts ON spans(session_id, ts);
CREATE INDEX IF NOT EXISTS idx_spans_project_ts ON spans(project_id, ts DESC);
